### ISSUE TITLE
SPAAS Telemetry is EVIL

### ISSUE THREAD

**Issue by h1z1** [LINBIT/drbd#22]
Regarding SPAAS, how is it this was ever added with zero documentation and defaults to Enabled??

https://github.com/LINBIT/drbd/commit/b5746201fcc144d99eff5706cbfbbc6744100d1b#diff-57a90809a4255d4d390b56b073ee315af871095885925f0bee235489fb97fc45R116

DRBD has been in the Kernel for a very, very long time.   Surely GIT is capable of satisfying what ever over complicated "patches" you're adding after?

I'm somewhat amazed this hasn't been picked up by others in the kernel world.

**Comment by chrboe** [comment]
What exactly are your concerns?

> Surely GIT is capable of satisfying what ever over complicated "patches" you're adding after?

I'll be happy to review your patches.

**Comment by h1z1** [comment]
> What exactly are your concerns?

That you've hijacked a piece of code that has been part of the kernel for a long time.    



> I'll be happy to review your patches.

Yes I"m sure you will, in devnull too.  The only patch that should be submitted is it's removal.

Please do point to the README you linked where it says anything about drbd.io or this telemetry.

**Comment by rck** [comment]
Maybe I can add some clarification / rationals behind that:

We have years/decades actually of experience in providing a "compat layer" for DRBD. It is a complicated and annoying task. Coccinelle is a really good tool to handle this compat layer. Ways better than any ifdef mess we had. We are not going to discuss that anyways, we have to maintain it, we chose our tools.

This only affects builds that happen out of tree, obviously that will never be needed for in tree DRBD (no matter what version of DRBD/kernel).

Distributions can (and depending on their paranoia should) generate a patch that matches their disto-kernel and apply it to our tarball/repackage it, however they roll. Then spatch (or its online variant on drbd.io) is not required, but the local patch is applied. They/you can always use `SPAAS=false` to disable it entirely.

And maybe one step back to the reasons: We ship pre-calculated patches for the most common distributions, if you use one of those then again there is no spatch involved. So who would even run into SPAAS? Users with a uncommon kernel (we don't already ship pre-calculated patches in the tarball) that **also** don't have access to a recent enough version of coccinelle/spatch. A typical user would be a Proxmox user that uses the dkms or tarball (too old Debian/coccinelle at the time + custom kernel).

Over time this will solve itself anyways. DRBD9 will get upstream eventually, then you don't need to build it out of tree if you don't like it, and as DRBD release cycles became faster and we are removing old distributions from the support matrix, we hopefully can just depend on a recent version of spatch in the future and don't need to depend on the online one.

So I think we
- have a very good reason to use spatch
- have a very good reason to provide the online version for users with an uncommon kernel and too old/no spatch
- provide ways for distributions/users to disable it / generate and ship their own patches (or they have spatch already)

So besides removing it (which we will not do now), how could we improve? Better documentation? Where would that be besides in the `README.md` in the building section?

**Comment by Philipp-Reisner** [comment]
Here is [the patch](https://github.com/LINBIT/drbd/commit/47b94d1fc623e1e67f249a70b7c18f55a98a4e78) that adds the relevant information to [README.md](https://github.com/LINBIT/drbd/blob/drbd-9.0/README.md) which gets displayed when you go to DRBD's git repo on github.

It says, Building DRBD ... From a release tarball ... 
_For all other kernels, you can use LINBIT's "spatch as a service" online service, which transparently and automatically generates compatibility patches based on your kernels feature set._
.. and goes on..
_or don't want to use "spatch as a service", you will have to install a recent version of coccinelle (see above)._
and that see above resolves to
_we require a very recent version of spatch (at least 1.0.8 at time of writing)_

**Comment by h1z1** [comment]
> So who would even run into SPAAS? Users with a uncommon kernel (we don't already ship pre-calculated patches in the tarball) that also don't have access to a recent enough version of coccinelle/spatch



Anyone who tries to build without an active network connection or as the message points out, anyone with a proper firewall given it doesn't use a standard port.

> Here is the patch that adds the relevant information to README.md which gets displayed when you go to DRBD's git repo on github.

There's nothing in that about drbd.io, and yes, as you point out, that is on Github.   

Everything about the language in that commit would lead one to believe it is optional.

"  you **can** use LINBIT's "spatch as a service" online "  


The implementation however differs and defaults to TRUE.

https://github.com/LINBIT/drbd/blob/be52fd979504061bfa9a899e266e314f0aee4cac/drbd/drbd-kernel-compat/gen_compat_patch.sh#L114


https://github.com/LINBIT/drbd/blob/1ebc69dc191fcfc0c98cb8d4c74f67064573ac10/drbd/Makefile#L42

The logic is reversed if the intent was to be optional.  Certainly not informed consent.

**Comment by rck** [comment]
> > So who would even run into SPAAS? Users with a uncommon kernel (we don't already ship pre-calculated patches in the tarball) that also don't have access to a recent enough version of coccinelle/spatch

> Anyone who tries to build without an active network connection or as the message points out, anyone with a proper firewall given it doesn't use a standard port.

As this quotes parts of my answer I guess your text should be related to that? I don't see how it relates, but taking just what you wrote: it simply is wrong. Once more, you don't run into SPASS if:
- you have a proper patch for your kernel (maybe already shipped by us, or you could generate it on another machine (with a local coccinelle or SPAAS (in the later case the exercise would be pretty pointless obviously) from the other machine's `config.h`).
- you have a recent enough coccinelle installed locally.

Both has absolutely nothing to do with your network connection or your firewall. If your build system does not have internet access which is the case for most distrubution package builders, then again: generate the patch however you like and make sure it is part of the tarball/patches you apply on top of the orig tarball. Then the build system finds it and will not bother to call out to SPAAS; **or** have a recent copy of `spatch`, then, again, this locally installed spatch will be used instead of the online service that does exactly the same. what the locally installed one would do.

So consulting `/dev/crystalball`, I would assume that you want:
- install a recent enough version of coccinelle (some distros call it spatch) locally so that it can be used if we don't already ship a patch as part of the tarball
- set `make KDIR=... SPAAS=false` so that even if everthing (no local patches, no/or too old spatch) wents wrong you don't run into SPAAS.

The default of being enabled was not taken lighthearted, but module building usually is not an interactive process. `dkms` building is a pretty important for some of our users.

So, my summary would be: We have a reason to fall back to the online service "in the worst case" as the last resort. And even more importantly we provide enough ways to opt out. Maybe we should communicate "the worst case" better. Documentation patches welcome.

**Comment by h1z1** [comment]
> As this quotes parts of my answer I guess your text should be related to that? I don't see how it relates, but taking just what you wrote: it simply is wrong. Once more, you don't run into SPASS if:

It relates because you're claiming for some bizzare reason that the service is optional.  I'm telling you it wasn't.

> So consulting /dev/crystalball, I would assume that you want:

Your crazyball lies.  

>install a recent enough version of coccinelle (some distros call it spatch) locally so that it can be used if we don't already ship a patch as part of the tarball

Great.  I'd have no problem doing that IF YOU WARNED USERS FIRST.   Indeed, distros DO ship either with their own version of whatever patches you're pushing, or spatch.

> set make KDIR=... SPAAS=false so that even if everthing (no local patches, no/or too old spatch) wents wrong you don't run into SPAAS.

That should be the DEFAULT, thus opt-in not opt-out.  Like I said, your logic behind what you claim the service does and how it was implemented is backward..  Starting to believe it was intentional too.   DRBD has been in the kernel for a long time, this "feature" was introduced in 2020.

> So, my summary would be: We have a reason to fall back to the online service "in the worst case" as the last resort. And even more importantly we provide enough ways to opt out

And that is the problem.  It wasn't worst case, there was no option to "opt-in".    Seriously this stinks.

There are many other projects that are maintained outside the kernel.   ZFS is an example of one and they do not resort to this level of ... crazyness.   Your claim that your patches are so specialized they do not work with git, should be setting alarm bells off.

**Comment by raltnoeder** [comment]
> It relates because you're claiming for some bizzare reason that the service is optional. I'm telling you it wasn't.

I'm telling you it is optional, because I currently compile DRBD 9.x without using that service. If it were not optional, then that would not be possible.

> Great. I'd have no problem doing that IF YOU WARNED USERS FIRST.

Warn users about what?
_You are going to download some modifications from the internet while you are compiling a program that you just downloaded from the internet?_

> DRBD has been in the kernel for a long time, this "feature" was introduced in 2020.

DRBD 8.x has been in the kernel for a long time. DRBD 9.x has not ever been in the kernel, it's optional software that you downloaded from us, or from some mirror. While you're compiling it, it will, by default, effectively download more stuff from us.

> And that is the problem. It wasn't worst case, there was no option to "opt-in". Seriously this stinks.

I mean, driver-development-wise, the Linux kernel is already kind of a worst case, because every minor modification/version of the kernel is incompatible to every other minor modification/version of the same kernel by design, which is the root cause that even makes all of this patching insanity necessary. It's kind of designed so that you don't really know what code base you're really running, because every minor modification/version of it is running something else.
If you really want to know what exactly the code base is that your system is running, you're using the wrong operating system for that, because it's not designed to do that for you.

**Comment by h1z1** [comment]
> > It relates because you're claiming for some bizzare reason that the service is optional. I'm telling you it wasn't.
> 
> I'm telling you it is optional, because I currently compile DRBD 9.x without using that service. If it were not optional, then that would not be possible.
> 

And yet you say nothing of the environment you're using.  

I would love for the patches to be part of the kernel source or git.  THey aren't.  That's in part the whole point of this charade.

> > Great. I'd have no problem doing that IF YOU WARNED USERS FIRST.
> 
> Warn users about what? _You are going to download some modifications from the internet while you are compiling a program that you just downloaded from the internet?_
> 

Yes?  Are you really this dense?   It wasn't downloaded from the internet, it was copied from another host.


> > DRBD has been in the kernel for a long time, this "feature" was introduced in 2020.
> 
> DRBD 8.x has been in the kernel for a long time. DRBD 9.x has not ever been in the kernel, it's optional software that you downloaded from us, or from some mirror. While you're compiling it, it will, by default, effectively download more stuff from us.
> 

I'm aware of that and it is a contradiction from the intent.   Dare I say misleading lie.


> > And that is the problem. It wasn't worst case, there was no option to "opt-in". Seriously this stinks.
> 
> I mean, driver-development-wise, the Linux kernel is already kind of a worst case, because every minor modification/version of the kernel is incompatible to every other minor modification/version of the same kernel by design, which is the root cause that even makes all of this patching insanity necessary.

What on Earth are you talking about?   Code doesn't get into the kernel unless it compiles.  Period.   You may know of a guy Linus Torvalds.

As I've said before there are many projects maintained outside the kernel entirely.   ZFS was one, NVIDIA is another.  


> It's kind of designed so that you don't really know what code base you're really running, because every minor modification/version of it is running something else. If you really want to know what exactly the code base is that your system is running, you're using the wrong operating system for that, because it's not designed to do that for you.

Thankfully there are organizations whom disagree with you.  You might want to check with the Free Software Foundation before making such insane statements.  For example.

**Comment by lge** [comment]
A short history of SPAAS:

DRBD development happens out out tree.
There are reasons for that. We intend to get DRBD 9 in-tree eventually. Off topic here.

We want to be compatible with a range of kernel versions. Which means we need a compat layer. This compat layer accumulated a lot of problems over the years.

In early 2018, we switched to using spatch (coccinelle) for our compat layer. We feel that is a big improvement, making the resulting patches more reliable and also making it easier to maintain that compat layer.

People complained that they could no longer compile DRBD from source, because they where unable to run a suitable spatch during their build process (for reasons).
So late in 2019 (1.5 years later), as a convenience, we added a fallback to "spatch-as-a-service", because people seemed to be able to use curl during their build process more easily than spatch. We were unhappy with the unconditional call to spatch-as-a-service, so a few days later, we added the SPAAS conditional to optionally disable that fallback.

The build process needs an spatch run in one of two situations.
If run from a git checkout -- this spatch run is always done locally.
Or if run from an extracted release tarball, and the config check results do not match any of the pre-generated spatch outputs we ship with the release tarball. This spatch run can be done locally as well.
But in this case, we also can fallback to the "spatch-as-a-service" thingy.
What it needs is the result of the config checks (the generated config.h), and the version of the DRBD release tarball. It then generates the spatch output on that service box, caches for reuse with the same `config.h` output, and returns the spatch output to the caller.

Why don't we pre-generate all possible patches then?
Because that would be quite an insane number of patches.
We currently have 90? 100? compat tests. You are smart, do the combinatorial math yourself.

We obviously had a choice there: do that fallback to the online service by default (opt-out of the _fallback_).
Or require people to set something to actually do that fallback to the online service if so desired (opt-in into the _fallback_).

You strongly believe we should not have that fallback at all, or at leaste have chosen "explicit opt-in to the fallback, even though it is only a fallback anyways". Okay.

We _intentionally_  chose to have the _fallback_ use the online service by default (opt-out), because in our experience, people in general do not read anything, no readme, no plain English error messages, no "this is what you can do about it" hints. But complain with as much detail as "it does not work", without even saying what any of _it_ or _work_ may be on that particular occasion. But complain they do, and loudly. D'oh.

Now, you insinuate we do that for EVIL motives.
To do ... what exactly? "_Telemetry_"? Of what? What information could we possibly gain?
At this particular *time*, someone behind that *IP* tried to build DRBD from a release tarball of *version X* against a kernel config that lead to this *compat check result*, which did not match any of the pre-generated patches we ship in that particular release tarball.
Whoa. That is fucking insane. Think about all the cool stuff we could do with that information.
(while missing out on all the funny details of who might using binary packages, or compiling DRBD from a git checkout, or against "common" kernels, or without the ability to use curl against port 2020, or which OS they run, or ...).

We may be naive, but we don't. It is a convenience service only.
Also convenience for us, actually, so we do not need to explain again and again what to do to "make it build".

You chose to not believe that.
That is totally fine, you are of course free to mistrust everyone and see evil motives everywhere.
But, are you sure you don't draw conclusions from yourself about others?

**Comment by raltnoeder** [comment]
> And yet you say nothing of the environment you're using.

That was on a quite plain Rocky Linux 8.4 "Green Obsidian" install with an OCaml compiler, version 4.13.1, and Coccinelle (aka spatch) version 1.1.1 custom-compiled, using findlib 1.9.1, which Coccinelle requires as a dependency. The DRBD source used is simply a git clone from what's on our GitHub account.

You are free to try and see for yourself that you can compile DRBD without using SPAAS using that kind of setup.

> I would love for the patches to be part of the kernel source or git. THey aren't. That's in part the whole point of this charade.

All the input files for spatch are in the DRBD git repository. Those files, together with spatch, are the source of those patches.

> Yes? Are you really this dense? It wasn't downloaded from the internet, it was copied from another host.

...and how do you suggest it got on this other host in the first place?

> What on Earth are you talking about? Code doesn't get into the kernel unless it compiles. Period. You may know of a guy Linus Torvalds.

The information you are looking for is binary compatibiliy of the kernel with loadable modules, which most operating systems have to some extent, and Linux normally does not (there are exceptions, e.g., RedHat says they try to keep binary compatibility with modules, which is mostly true, but sometimes did break despite their efforts). And that, in general, is the reason why the code for loadable modules, such as DRBD 9.x, must be modified in different ways, depending on the version and configuration of the Linux kernel, to match a specific compile of the kernel. In contrast to that, many other operating systems support the loading of the same, unmodified code as a kernel module in a range of different versions and configurations of the kernel, or they are designed to run modules/drivers isolated from the kernel in the first place, and in both those cases, no patching of module code is needed within a range of different versions or configurations of the kernel of such operating systems.

> Thankfully there are organizations whom disagree with you. You might want to check with the Free Software Foundation before making such insane statements. For example.

There was nothing insane about my statement, the problem was that you did not understand what I was talking about in my first statement. It's now described in greater detail in the paragraph that I wrote above. The second statement that you are referring to here is only a logical consequence of the first one.

**Comment by h1z1** [comment]
> A short history of SPAAS:
> 
> DRBD development happens out out tree. There are reasons for that. We intend to get DRBD 9 in-tree eventually. Off topic here.
> 

It's not off topic if the way you view patches in shrouded in secrecy.

> We want to be compatible with a range of kernel versions. Which means we need a compat layer. This compat layer accumulated a lot of problems over the years.
> 

Out of tree code tends to do that.   As I mentioned, drbd is not the only project to run afoul with the Kernel API.   It is however one of few that has _any_ code in there to begin with.  Neither NVIDIA nor ZFS for example do.  I don't believe even reiser was added until much later (politics of that one are offtopic here).

> In early 2018, we switched to using spatch (coccinelle) for our compat layer. We feel that is a big improvement, making the resulting patches more reliable and also making it easier to maintain that compat layer.
> 
> People complained that they could no longer compile DRBD from source, because they where unable to run a suitable spatch during their build process (for reasons). So late in 2019 (1.5 years later), as a convenience, we added a fallback to "spatch-as-a-service", because people seemed to be able to use curl during their build process more easily than spatch. We were unhappy with the unconditional call to spatch-as-a-service, so a few days later, we added the SPAAS conditional to optionally disable that fallback.


You created your own problem to solve it with your own telemetry ridden solution. 

> 
> The build process needs an spatch run in one of two situations. If run from a git checkout -- this spatch run is always done locally. Or if run from an extracted release tarball, and the config check results do not match any of the pre-generated spatch outputs we ship with the release tarball. This spatch run can be done locally as well. But in this case, we also can fallback to the "spatch-as-a-service" thingy. What it needs is the result of the config checks (the generated config.h), and the version of the DRBD release tarball. It then generates the spatch output on that service box, caches for reuse with the same `config.h` output, and returns the spatch output to the caller.

I agree, you _CAN_.  Problem is it defaults to doing that.  

> 
> Why don't we pre-generate all possible patches then? Because that would be quite an insane number of patches. We currently have 90? 100? compat tests. You are smart, do the combinatorial math yourself.
> 

Sounds like your build / CI system sucks?  Not to keep referring to ZFS as an example (the have their own problems), but they literally DO test, extensively.   There's even their own portability layer between Solaris and OS's that don't kill kittens.

> We obviously had a choice there: do that fallback to the online service by default (opt-out of the _fallback_). Or require people to set something to actually do that fallback to the online service if so desired (opt-in into the _fallback_).
> 

You're conflating users whom apparently make such substantial changes that they're unable to port them either upstream, or suffer the same self-inflicted troubles as you.   Yet you refer to people "who just want to compile it".   Those are different groups.

> You strongly believe we should not have that fallback at all, or at leaste have chosen "explicit opt-in to the fallback, even though it is only a fallback anyways". Okay.
> 

Those are rather oddly contradicting tings.  I never said I was against the fallback, but yes, it should be OPT OUT.  

> We _intentionally_ chose to have the _fallback_ use the online service by default (opt-out), because in our experience, people in general do not read anything, no readme, no plain English error messages, no "this is what you can do about it" hints.

So you admit it's not optional then?  Now I'm confused.

> But complain with as much detail as "it does not work", without even saying what any of _it_ or _work_ may be on that particular occasion. But complain they do, and loudly. D'oh.
>

Who complained??  The rightful answer to anyone whom changed their kernel such that the API/ABI itself changes, would be "go pound salt".  Aka unsupported.   There is an argument to be had based on your own admission that the paches themselves are overly complicated.
 
>> Now, you insinuate we do that for EVIL motives. To do ... what exactly? "_Telemetry_"?

> Of what? What information could we possibly gain? At this particular _time_, someone behind that _IP_ tried to build DRBD from a release tarball of _version X_ against a kernel config that lead to this _compat check result_, which did not match any of the pre-generated patches we ship in that particular release tarball. Whoa. That is fucking insane.

I know it's insane.. so why do you collect it?  Why do you not disclose that it's happening before doing so?   Why are you somehow surprised privacy is important? (and arguably security).

>  Think about all the cool stuff we could do with that information. (while missing out on all the funny details of who might using binary packages, or compiling DRBD from a git checkout, or against "common" kernels, or without the ability to use curl against port 2020, or which OS they run, or ...).
> 

Except, it was against a stock kernel.  I'm not about to tell you how it can be abused but will point out Solarwinds was a thing.  Can't really help you if you don't understand the reference.

> We may be naive, but we don't. It is a convenience service only. Also convenience for us, actually, so we do not need to explain again and again what to do to "make it build".
> 

That is your own doing though.  You wouldn't need to if you'd said why the build failed... by default.

> You chose to not believe that. That is totally fine, you are of course free to mistrust everyone and see evil motives everywhere. But, are you sure you don't draw conclusions from yourself about others?

No I think this thread speaks _volumes_.   Hopefully the powers that be take note because it's absolutely frightening how this is in the kernel.

cheers
