### ISSUE TITLE
Include compat patch cache for RHEL 8.6 kernel version 4.18.0-372

### ISSUE THREAD

**Issue by ipaq3870** [LINBIT/drbd#39]
Not sure if this is the right place to ask.

The drbd-9.1.7 download on Linbit website (not the github release) does not include a compat patch cache for RHEL 8.6 kernel version 4.18.0-372. I understand that RHEL 8.6 was released in mid-May after drbd-9.1.7, can Linbit include such cache for the RHEL 8.6 kernel in the later release say drbd-9.1.8?

We need to use the patch cache in our build system that don't have coccinelle or Internet to use spatch-as-a-service. Thanks.

**Comment by rck** [comment]
sure 9.1.8 will include that. it was too late for 9.1.7, we only included it in our internal build system so that our customers get prebuilt kmods for RHEL 8.6/9.0. IIRC there was no need for actual compat work, just to generate a patch for that kernel. So you might be able to generate you own "release tarball". Sorry, not sure if it still works as described here: https://linbit.com/blog/how-to-make-drbd-compatible-to-the-linux-kernel/ . Maybe the simple solution is to let it build on a RHEL 8.6 that is connected to the internet and runns into spatch-as-a-service. and from there you take the generated patch and copy it to the others from the source tarball and re-tar that again.

Closing this here as 9.1.8 will include it, if there are still questions, you can for sure ask here.
