### ISSUE TITLE
drbd is losing packages on resync

### ISSUE THREAD

**Issue by harridu** [LINBIT/drbd#68]
According to the documentation for 8.4 it is sufficient to disconnect and reconnect the secondary to resolve out-of-sync sectors discovered by "drbdadm verify". Apparently this introduces new out-of-sync sectors, as a subsequent verify shows.

drbd is not fully synchronized. It is losing packages.

This is a fatal problem for my setup.

**Comment by harridu** [comment]
[logfile.txt](https://github.com/LINBIT/drbd/files/12387410/logfile.txt)

**Comment by dvance** [comment]
If the volume you’re checking is actively used, you might see a few false positives in the log messages.

This is because data blocks might have been changed by the application in RAM after submitting the write request (but before getting it acknowledged!), and so would compare different generations of the data. If you do this check eg. every week and get different block numbers every time, you’re fine. If you get the same block number(s), your storage might have stuck bits, and be unable to correctly write data in these blocks.

The log messages give you the start number. You should be able to properly verify if there is in fact an issue by copying the specific blocks via 'dd' and comparing them on both nodes.

**Comment by harridu** [comment]
This is an annoying problem. If there are false out-of-sync warnings then nobody trusts these warnings anymore.
